### ISSUE TITLE
EPIC: Add full validations

### ISSUE THREAD

**Issue by maurolacy** [babylonlabs-io/cosmos-bsn-contracts#7]
**[<img src="https://avatars.githubusercontent.com/u/11656534?s=17&v=4" width="17" height="17"> @maurolacy](https://www.github.com/maurolacy)** cloned issue [babylonchain/babylon-contract#84](https://www.github.com/babylonchain/babylon-contract/issues/84) on 2024-05-03: 

> After basic validations (#82), let's complete the validation logic after the original Go code.
> 
> 
> 
> Related to #82. Also, likely requires #76.

**Comment by SebastianElvis** [comment]
After #46 and #56, most of the reality checks are done (feature flag for lite/full version, correctness of BTC staking library, etc..).

The following includes the missing verification rules. Those will be picked up later.

## Finality provider registration request

- [ ] Verify PoP

## BTC delegation request

- [ ] Ensure staking tx is included the BTC light client
- [ ] Ensure staking tx is k-deep
- [ ] Ensure staking tx timelock has more than w BTC blocks left
- [ ] Verify PoP
- [ ] Verify covenant signatures over slashing tx
- [ ] Ensure unbonding time is max(min_unbonding_time, w)
- [ ] Ensure unbonding tx is spending the given staking tx
- [ ] Ensure consistency bweteen unbonding tx and unbonding slashing tx
- [ ] Verify staker's signature over slashing path of unbonding tx
- [ ] Verify covenant signatures over unbonding slashing tx
- [ ] Ensure unbonding tx fee is not too low

## BTC undelegation request

- [ ] Ensure BTC delegation is active
- [ ] Verify staker's signature over the unbonding tx

## Slashed BTC delegation

- [ ] Ensure BTC delegation is active
- [ ] Verify the evidence of the equivocating FP

**Comment by maurolacy** [comment]
There are a number of TODOs in the apis `validate` module. Listing here for visibility:

- https://github.com/babylonlabs-io/babylon-contract/blob/50ba8d7a24cf595a3e9694f66fa0d9f73fda0ed9/packages/apis/src/validate.rs#L29-L31.
- https://github.com/babylonlabs-io/babylon-contract/blob/50ba8d7a24cf595a3e9694f66fa0d9f73fda0ed9/packages/apis/src/validate.rs#L33-L37.
- https://github.com/babylonlabs-io/babylon-contract/blob/50ba8d7a24cf595a3e9694f66fa0d9f73fda0ed9/packages/apis/src/validate.rs#L33-L37
- https://github.com/babylonlabs-io/babylon-contract/blob/50ba8d7a24cf595a3e9694f66fa0d9f73fda0ed9/packages/apis/src/validate.rs#L128
- https://github.com/babylonlabs-io/babylon-contract/blob/50ba8d7a24cf595a3e9694f66fa0d9f73fda0ed9/packages/apis/src/validate.rs#L137

**Comment by liuchengxu** [comment]
In which case should the lite version be used? Will the lite version be removed once the full validation version is complete?

**Comment by SebastianElvis** [comment]
Side note: PoP is no longer necessary. 

PoP is used for binding the Babylon address to the BTC PK for reward distribution. The current design allows Babylon to do reward distribution so BSN side does not need to do anything about Babylon address now

**Comment by SebastianElvis** [comment]
Not relevant anymore as we are going with lite version for now
