### ISSUE TITLE
EPIC: tasks for Cosmos integration readiness

### ISSUE THREAD

**Issue by SebastianElvis** [babylonlabs-io/cosmos-bsn-contracts#84]
## High priority features

- [x] https://github.com/babylonlabs-io/babylon-contract/issues/7
- [x] https://github.com/babylonlabs-io/babylon-contract/issues/54
- [x] https://github.com/babylonlabs-io/cosmos-bsn-contracts/issues/90
- [x] https://github.com/babylonlabs-io/babylon-contract/issues/19
- [x] https://github.com/babylonlabs-io/cosmos-bsn-contracts/issues/157

## Bugs

- [ ] https://github.com/babylonlabs-io/cosmos-bsn-contracts/issues/156
- [x] https://github.com/babylonlabs-io/cosmos-bsn-contracts/issues/143
- [x] https://github.com/babylonlabs-io/cosmos-bsn-contracts/issues/66
- [x] https://github.com/babylonlabs-io/cosmos-bsn-contracts/issues/115

## Nice to have

- [ ] https://github.com/babylonlabs-io/cosmos-bsn-contracts/issues/127
- [ ] https://github.com/babylonlabs-io/babylon-contract/issues/99
- [ ] https://github.com/babylonlabs-io/babylon-contract/issues/55
- [ ] https://github.com/babylonlabs-io/babylon-contract/issues/17
- [ ] https://github.com/babylonlabs-io/babylon-contract/issues/3
- [ ] https://github.com/babylonlabs-io/babylon-contract/issues/2
- [ ] https://github.com/babylonlabs-io/babylon-contract/issues/1
- [ ] https://github.com/babylonlabs-io/babylon-contract/issues/103

**Comment by SebastianElvis** [comment]
Closing as big chunk of work is done or becomes irrelevant due to the decision on trusted integrtaion
